112 implementing a css library and summarize all distributed css snippets
ASKnetCommunity/Training pull request #116
Opened 2023-11-06 14:57 UTC by bmen

I installed Bootstrap and merged all the distributed CSS snippets.
The training configurator is completely separate from the rest of the pages and uses the layout, CSS and JS "trainingsplan.*"

The styling of the other pages (except training plan) are controlled by the _sass/main.sass file.

In the readme under the heading: "Styling (CSS, SASS, etc.)" you will find a short description of how a styling can be changed.

2023-11-09 07:31 UTC, saisilinus commented on README.md
A couple of things. I talked with @timmwille about removing the `.vscode` folder from `.gitignore`  so that we can add the settings there and adjust them for all users at once. It will be convenient and consistent.

Something else that would be more convenient is a `recommendations.json` file in `.vscode` that automatically suggests to a developer to install the extension. Something like this:

```json
{
	// See https://go.microsoft.com/fwlink/?LinkId=827846 to learn about workspace recommendations.
	// Extension identifier format: ${publisher}.${name}. Example: vscode.csharp
	// List of extensions which should be recommended for users of this workspace.
	"recommendations": [
		"glenn2223.live-sass"
	],
	// List of extensions recommended by VS Code that should not be recommended for users of this workspace.
	"unwantedRecommendations": []
}
```

2023-11-09 08:05 UTC, saisilinus requested changes
It looks neat and should definitely provide a better development experience.

## BUG
One thing though. The `Home` page is broken. This is what it looked like before:

![Screenshot from 2023-11-09 10-49-12](https://github.com/ASKnetCommunity/Training/assets/42277372/b24776fd-ab6a-42fb-938c-1c94c48bcf70)

This is what it looks like now:

![Screenshot from 2023-11-09 10-49-37](https://github.com/ASKnetCommunity/Training/assets/42277372/3acd3172-da79-4856-9367-6c4cdcac747a)

![Screenshot from 2023-11-09 10-49-44](https://github.com/ASKnetCommunity/Training/assets/42277372/c6420506-d89e-4ca8-931d-a0e1f35b997a)

Otherwise everything I've tested works as before.

## OPTIONAL CHANGE
Consider removing `.vscode` from `.gitignote` and adding an `extensions.json` in `.vscode` with the recommended extension. I have talked about this extensively in another [comment](https://github.com/ASKnetCommunity/Training/pull/116/files#r1387589525).

2023-11-09 17:49 UTC, merged

2023-11-09 21:59 UTC, bmen commented
> It looks neat and should definitely provide a better development experience.
> 
> ## BUG
> One thing though. The `Home` page is broken. This is what it looked like before:
The homepage is not broken. It is only rebuilt in bootstrap. we can still redesign it. I'm currently working on the modules page anyway. There are now also questions about the design. colours, fonts, etc. If we have defined a design, then we can adapt the home page to this design.

by the way, I am currently working in this branch. If anyone wants a sneak preview on http://localhost:4000/modules/ ;)
git checkout 111-create-an-overview-page-where-all-modules-are-displayed

2023-11-09 22:18 UTC, bmen commented
> ## OPTIONAL CHANGE
> Consider removing `.vscode` from `.gitignote` and adding an `extensions.json` in `.vscode` with the recommended extension. I have talked about this extensively in another [comment](https://github.com/ASKnetCommunity/Training/pull/116/files#r1387589525).

as far as I'm concerned. Remove the entry in the gitignore. Please create an issue -> branch -> pull request ;)

2023-11-10 08:01 UTC, saisilinus commented
> > It looks neat and should definitely provide a better development experience.
> > ## BUG
> > One thing though. The `Home` page is broken. This is what it looked like before:
> 
> The homepage is not broken. It is only rebuilt in bootstrap. we can still redesign it. I'm currently working on the modules page anyway. There are now also questions about the design. colours, fonts, etc. If we have defined a design, then we can adapt the home page to this design.
> 
> by the way, I am currently working in this branch. If anyone wants a sneak preview on http://localhost:4000/modules/ ;) git checkout 111-create-an-overview-page-where-all-modules-are-displayed

Cool